services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
    volumes:
      - /mnt/storage/docker/plex:/config
      - /mnt/storage/media/movies:/data/movies
      - /mnt/storage/media/movies-3d:/data/movies-3d
      - /mnt/storage/media/tv:/data/tv
      - /mnt/storage/media/music:/data/music
      - /mnt/storage/media/home-videos:/data/home-videos
    restart: unless-stopped
  
 qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /mnt/storage/docker/qbittorrent:/config
      - /mnt/storage/downloads:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/storage/docker/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/storage/docker/sonarr:/config
      - /mnt/storage/media/tv:/tv
      - /mnt/storage/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/storage/docker/radarr:/config
      - /mnt/storage/media/movies:/movies
      - /mnt/storage/media/movies-3d:/movies-3d
      - /mnt/storage/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/storage/docker/bazarr:/config
      - /mnt/storage/media/movies:/movies
      - /mnt/storage/media/tv:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/storage/docker/overseerr:/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - TZ=America/New_York
    volumes:
      - /mnt/storage/media/audiobooks:/audiobooks
      - /mnt/storage/media/music:/music
      - /mnt/storage/docker/audiobookshelf:/config
      - /mnt/storage/docker/audiobookshelf/metadata:/metadata
    ports:
      - "13378:80"
    restart: unless-stopped

     gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=SKMEsmR8Z1g0lAxuyxGBKeaORGG7o+C2p3YBDaRTw2o=
      - WIREGUARD_ADDRESSES=10.66.173.34/32,fc00:bbbb:bbbb:bb01::3:ad21/128
      - SERVER_COUNTRIES=United States
    volumes:
      - /mnt/storage/docker/gluetun:/gluetun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

